name: Close linked issues if on a release branch
on:
    pull_request:
        branches:
            - 'release_*'
        types: [closed]
jobs:
    close_linked_issues:
        runs-on: ubuntu-latest
        steps:
            - name: Install jq
              run: sudo apt-get install -y jq
            - uses: octokit/graphql-action@v2.x
              id: get_linked_issues
              name: Get linked issues
              with:
                  query: |
                      {
                      resource(url: "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/pull/${{ github.event.number }}") {
                          ... on PullRequest {
                          timelineItems(itemTypes: [CONNECTED_EVENT, DISCONNECTED_EVENT], first: 250) {
                              nodes {
                              ... on ConnectedEvent {
                                  id
                                  __typename
                                  subject {
                                  ... on Issue {
                                      number
                                  }
                                  }
                              }
                              ... on DisconnectedEvent {
                                  id
                                  __typename
                                  subject {
                                  ... on Issue {
                                      number
                                  }
                                  }
                              }
                              }
                          }
                          }
                      }
                      }
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Close linked issues
              run: |
                  linked_issues="$(echo "$LINKED_ISSUES")"

                  connectedIssues=()
                  disconnectedIssues=()

                  mapfile -t connectedIssues < <(echo "$linked_issues" | jq -r '.resource.timelineItems.nodes[] | select(.__typename == "ConnectedEvent") | .subject.number')
                  mapfile -t disconnectedIssues < <(echo "$linked_issues" | jq -r '.resource.timelineItems.nodes[] | select(.__typename == "DisconnectedEvent") | .subject.number')

                  unique_connectedIssues=()
                  for issue in "${connectedIssues[@]}"; do
                    if [[ ! " ${disconnectedIssues[@]} " =~ " $issue " ]]; then
                      unique_connectedIssues+=("$issue")
                    fi
                  done

                  for issue in "${unique_connectedIssues[@]}"; do
                    gh issue close "$issue"
                  done
              env:
                  LINKED_ISSUES: ${{ steps.get_linked_issues.outputs.data }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
